version: "3.2"
services:
  selenium:
    image: selenium/standalone-chrome
    container_name: selenium
    shm_size: 2gb
    privileged: true
    restart: always
    volumes:
        - type: bind
          source: ./logs/
          target: /logs/
    environment:
        - TZ=Europe/Zurich
  bot:
    image: asvz-enroller
    build: .
    container_name: asvz-enroller
    restart: always
    ports:
        - "5090:5000"
    volumes:
        - type: bind
          source: ./instance/
          target: /instance/
        - type: bind
          source: ./logs/
          target: /logs/
    depends_on:
        - selenium