version: "3"
services:
  web:
    image: asvz-enroller
    build: .
    container_name: asvz-enroller
    restart: always
    ports:
        - "5090:5000"
    volumes:
      - instance/:/instance/
      - logs/:/logs/